markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: emillylearn2016
author: "Emily"
email: emilylearn2016@gmail.com
name: "一只Emily"


all_categories: [
["self-management", "自我管理","/posts/self-managemen.html"], 
["program", "软件编程","/posts/program.html"],
["pinbu", "拼布","/posts/拼布.html"], 
["real-estate", "房地产相关","/posts/real-estate.html"],
["read", "读书笔记","/posts/read.html"], 
["run&plank", "跑步运动","/posts/run&plank.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
